/* RAFECUT — site data (Mosul).
   Each item has Arabic fields plus an `en` object for English.
   Images: put your photos in the paths below (see images/README.md).
   Until a photo exists, the card shows a styled placeholder. */

const photo = (path) => `images/${path}`;

/* Area keys are used for filtering; labels come from i18n.js */
const AREAS = ["oldcity", "tayaran", "bartella", "hamdaniya"];

const SERVICES = [
  { icon: "location", href: "#locations",
    title: "مواقع التصوير", text: "بيوت تراثية في الموصل القديمة، وبيوت سكنية في حي الطيران، وأزقة برطلة والحمدانية.",
    en: { title: "Filming Locations", text: "Heritage houses in Old Mosul, family homes in Al-Tayaran, and the old lanes of Bartella and Hamdaniya." } },
  { icon: "camera", href: "#equipment",
    title: "المعدات والفنيون", text: "كاميرات Sony وعدسات G Master وكاميرات وعدسات سينما، مع فنيين محترفين.",
    en: { title: "Equipment & Crew", text: "Sony cameras, G Master lenses, cinema cameras and cine lenses, with skilled technicians." } },
  { icon: "hotel", href: "#hospitality",
    title: "الفنادق والمطاعم", text: "إقامة وإعاشة لفريقك في الموصل بالقرب من موقع التصوير وبحسب ميزانيتك.",
    en: { title: "Hotels & Dining", text: "Accommodation and catering for your team in Mosul, near set and on your budget." } },
  { icon: "film", href: "#post",
    title: "المونتاج والتلوين", text: "مونتاج وتصحيح ألوان ومؤثرات بصرية وتصميم صوتي باحترافية.",
    en: { title: "Editing & Color", text: "Professional editing, color grading, visual effects and sound design." } },
];

/* Every location rents for $100 per day */
const LOCATION_RATE = 100;

const LOCATIONS = [
  { area: "oldcity", type: "heritage", img: photo("locations/oldcity-courtyard-house.jpg"),
    name: "بيت موصلي بفناء داخلي — محلة جامع النوري",
    desc: "حوش مفتوح وأقواس وأعمدة من المرمر الموصلي (الحلان) على بُعد خطوات من جامع النوري الكبير.",
    en: { name: "Courtyard House — Al-Nuri Mosque Quarter",
      desc: "Open courtyard, arches and Mosul-marble columns, steps from the Great al-Nuri Mosque." } },
  { area: "oldcity", type: "heritage", img: photo("locations/oldcity-shanasheel-house.jpg"),
    name: "بيت الشناشيل والإيوان — قرب منارة الحدباء",
    desc: "واجهة بشناشيل خشبية وإيوان مطل على الفناء، مناسب للمشاهد الدرامية والتاريخية.",
    en: { name: "Shanasheel House with Iwan — near Al-Hadba Minaret",
      desc: "Carved wooden oriel windows and an iwan facing the courtyard, ideal for period drama." } },
  { area: "oldcity", type: "heritage", img: photo("locations/oldcity-sirdab.jpg"),
    name: "سرداب بيت موصلي قديم",
    desc: "قبو حجري بسقف معقود وإضاءة طبيعية خافتة من فتحات علوية.",
    en: { name: "Old Mosul House Cellar (Sirdab)",
      desc: "Vaulted stone cellar with soft natural light falling from high openings." } },
  { area: "oldcity", type: "street", img: photo("locations/oldcity-alley.jpg"),
    name: "أزقة المدينة القديمة — محلة جامع النوري",
    desc: "أزقة ضيقة بأبواب خشبية قديمة وجدران حجرية، للمطاردات واللقطات المتحركة.",
    en: { name: "Old City Lanes — Al-Nuri Quarter",
      desc: "Narrow lanes with old wooden doors and stone walls, for chases and tracking shots." } },
  { area: "tayaran", type: "residential", img: photo("locations/tayaran-garden-house.jpg"),
    name: "بيت عائلي بحديقة — حي الطيران",
    desc: "بيت حديث بحديقة أمامية وصالة واسعة، مناسب للدراما العائلية والإعلانات.",
    en: { name: "Family House with Garden — Al-Tayaran",
      desc: "Modern house with a front garden and a wide living room, suited to family drama and ads." } },
  { area: "tayaran", type: "residential", img: photo("locations/tayaran-two-storey.jpg"),
    name: "بيت سكني بطابقين — حي الطيران",
    desc: "مطبخ وغرف نوم وسطح مكشوف، يتيح تصوير عدة مشاهد في موقع واحد.",
    en: { name: "Two-Storey Home — Al-Tayaran",
      desc: "Kitchen, bedrooms and an open roof, so several scenes can be shot in one place." } },
  { area: "tayaran", type: "street", img: photo("locations/tayaran-street.jpg"),
    name: "شارع سكني هادئ — حي الطيران",
    desc: "شارع واسع تصطف عليه البيوت والأشجار، للقطات السيارات والمشي والحياة اليومية.",
    en: { name: "Quiet Residential Street — Al-Tayaran",
      desc: "A wide, tree-lined street of family homes, for driving, walking and everyday-life shots." } },
  { area: "bartella", type: "heritage", img: photo("locations/bartella-old-house.jpg"),
    name: "بيت برطلّي قديم من الجص والحجر",
    desc: "جدران من الحجر والجص وأبواب منقوشة وفناء صغير، بطابع سهل نينوى.",
    en: { name: "Old Stone & Gypsum House — Bartella",
      desc: "Stone and gypsum walls, carved doors and a small courtyard in the Nineveh Plains style." } },
  { area: "bartella", type: "street", img: photo("locations/bartella-lanes.jpg"),
    name: "أزقة برطلة القديمة",
    desc: "حارات ضيقة وبيوت متلاصقة وأبواب قديمة في قلب البلدة.",
    en: { name: "Bartella Old Lanes",
      desc: "Tight alleys, close-set houses and old doorways in the heart of town." } },
  { area: "hamdaniya", type: "heritage", img: photo("locations/hamdaniya-heritage-house.jpg"),
    name: "بيت تراثي في قره قوش (بغديدا)",
    desc: "بيت قديم بأقواس حجرية وفناء داخلي في مركز قضاء الحمدانية.",
    en: { name: "Heritage House — Qaraqosh (Bakhdida)",
      desc: "Old house with stone arches and an inner courtyard in the centre of Hamdaniya." } },
  { area: "hamdaniya", type: "residential", img: photo("locations/hamdaniya-family-house.jpg"),
    name: "بيت عائلي بحديقة — قره قوش",
    desc: "بيت سكني بحديقة وسطح، مناسب للمشاهد العائلية والإعلانات.",
    en: { name: "Family House with Garden — Qaraqosh",
      desc: "A family home with a garden and roof terrace, suited to domestic scenes and ads." } },
  { area: "hamdaniya", type: "street", img: photo("locations/hamdaniya-old-street.jpg"),
    name: "شارع قديم قرب كنيسة الطاهرة الكبرى",
    desc: "شارع تراثي بواجهات حجرية في محيط الكنيسة، للقطات الخارجية النهارية.",
    en: { name: "Old Street near the Grand Immaculate Church",
      desc: "A heritage street of stone façades around the church, for daytime exteriors." } },
];

/* qty = units available. Items without qty are suggestions; set their count when known. */
const GEAR = [
  { name: "Sony FX3", cat: "camera", qty: 3, price: 75, img: photo("gear/sony-fx3.jpg"),
    desc: "كاميرا سينمائية مدمجة فل فريم بتصوير 4K حتى 120 إطارًا", en: { desc: "Compact full-frame cinema camera, 4K up to 120 fps" } },
  { name: "Sony A7 IV", cat: "camera", qty: 4, price: 50, img: photo("gear/sony-a7iv.jpg"),
    desc: "كاميرا فل فريم 33 ميغابكسل بتصوير 4K 60p", en: { desc: "33 MP full-frame camera with 4K 60p video" } },
  { name: "Sony FE 24‑70mm f/2.8 GM II", cat: "lens", qty: 3, price: 25, img: photo("gear/sony-24-70-gm2.jpg"),
    desc: "عدسة زوم G Master متعددة الاستخدامات بفتحة f/2.8", en: { desc: "Versatile G Master f/2.8 standard zoom" } },
  { name: "Sigma 14‑24mm f/2.8 DG DN Art", cat: "lens", qty: 2, price: 25, img: photo("gear/sigma-14-24.jpg"),
    desc: "عدسة واسعة جدًا بتركيبة Sony E للمساحات الضيقة والمعمار", en: { desc: "Ultra-wide zoom for Sony E, for tight rooms and architecture" } },
  { name: "Sony FX6", cat: "cine", price: 100, img: photo("gear/sony-fx6.jpg"),
    desc: "كاميرا سينمائية فل فريم بفلتر ND إلكتروني مدمج", en: { desc: "Full-frame cinema camera with built-in electronic ND" } },
  { name: "Canon EOS C70", cat: "cine", price: 100, img: photo("gear/canon-c70.jpg"),
    desc: "حساس Super 35 بمدى ديناميكي عالٍ وتسجيل Cinema RAW Light", en: { desc: "Super 35 sensor, high dynamic range, Cinema RAW Light" } },
  { name: "Blackmagic URSA Mini Pro 12K", cat: "cine", price: 100, img: photo("gear/bmd-ursa-12k.jpg"),
    desc: "تسجيل Blackmagic RAW بدقة تصل إلى 12K", en: { desc: "Blackmagic RAW recording up to 12K" } },
  { name: "DZOFilm Vespid 25mm T2.1", cat: "cinelens", price: 50, img: photo("gear/vespid-25.jpg"),
    desc: "عدسة سينما ثابتة فل فريم بحلقات فوكس مسننة", en: { desc: "Full-frame cine prime with geared focus rings" } },
  { name: "DZOFilm Vespid 35mm T2.1", cat: "cinelens", price: 50, img: photo("gear/vespid-35.jpg"),
    desc: "البعد البؤري الأكثر استخدامًا في الدراما", en: { desc: "The go-to focal length for drama" } },
  { name: "DZOFilm Vespid 50mm T2.1", cat: "cinelens", price: 50, img: photo("gear/vespid-50.jpg"),
    desc: "عدسة طبيعية للحوارات واللقطات المتوسطة", en: { desc: "Natural perspective for dialogue and mid shots" } },
  { name: "DZOFilm Vespid 85mm T2.1", cat: "cinelens", price: 50, img: photo("gear/vespid-85.jpg"),
    desc: "عدسة بورتريه للقطات القريبة بخلفية ناعمة", en: { desc: "Portrait lens for close-ups with soft backgrounds" } },
  { name: "Sigma 18‑35mm T2 Cine", cat: "cinelens", price: 50, img: photo("gear/sigma-18-35-cine.jpg"),
    desc: "عدسة زوم سينمائية لحساسات Super 35", en: { desc: "Cine zoom for Super 35 sensors" } },
];

const CREW = [
  { icon: "camera", role: "مساعد كاميرا", desc: "تجهيز الكاميرا والعدسات، سحب الفوكس، وإدارة البطاقات والبطاريات.",
    en: { role: "Camera Assistant", desc: "Camera and lens prep, focus pulling, cards and batteries." } },
  { icon: "sound", role: "مهندس صوت", desc: "تسجيل الصوت في الموقع بمايك بوم ومايكات لاسلكية ومراقبة المستويات.",
    en: { role: "Sound Engineer", desc: "On-set recording with boom and wireless mics, monitoring levels." } },
  { icon: "lighting", role: "كفر لايت (Gaffer)", desc: "تصميم الإضاءة وتنفيذها مع مدير التصوير وإدارة الكهرباء في الموقع.",
    en: { role: "Gaffer", desc: "Designs and runs the lighting with the DP and manages power on set." } },
];

/* Real Mosul hotels and restaurants, compiled from published sources (see docs/mosul-hotels-restaurants.md).
   Included only when backed by two or more independent sources or a news report.
   Prices: only where a source stated one (USD); otherwise price is null = on request. */

/* Not listed: Nineveh International (Oberoi) — closed since 2017, awaiting reconstruction;
   Ashur Hotel — still being rebuilt (about 80% in late 2024). */
const HOTELS = [
  { name: "رامادا بلازا الموصل كورنيش", en: { name: "Ramada Plaza by Wyndham Mosul Corniche", area: "Tigris Corniche" }, area: "كورنيش دجلة", bank: "right", level: 3, price: 114, unit: "night",
    img: photo("hotels/ramada-plaza-mosul.jpg"), sources: ["https://www.iraq-businessnews.com/2025/07/21/pm-opens-ramada-plaza-hotel-in-mosul/", "https://www.wyndhamhotels.com/ramada/mosul-iraq/ramada-plaza-mosul-corniche/overview", "https://www.trip.com/hotels/mosul-hotel-detail-130082022/ramada-plaza-by-wyndham-mosul-corniche/", "https://www.booking.com/city/iq/al-mawsil.html", "https://iraqiguide.com/hotel/ramada-plaza", "https://www.iraq-businessnews.com/?p=235378", "https://www.tripadvisor.com/Hotel_Review-g303963-d33350287-Reviews-Ramada_Plaza_By_Wyndham_Mosul_Corniche-Mosul_Ninawa_Province.html"] },
  { name: "فندق مودرن بالاس", en: { name: "Modern Palace Hotel", area: "Al-Faisaliah Street" }, area: "شارع الفيصلية", bank: "left", level: 2, price: 51, unit: "night",
    img: photo("hotels/modern-palace.jpg"), sources: ["https://ph.trip.com/hotels/mosul-hotel-detail-122742465/modern-palace-hotel-1", "https://ae.trip.com/threestars/province/iq-nineveh.html", "https://www.readytotrip.com/hotels/Iraq/Mosul/modern-palace-hotel/", "https://againstthecompass.com/en/visit-mosul-iraq-after-liberation/", "https://sg.trip.com/hotels/mosul-hotels-list-86793/", "https://ae.trip.com/hotels/star3/city/iq/mosul.html", "https://www.tripadvisor.in/Hotel_Review-g303963-d33244731-Reviews-Modern_Palace_Hotel-Mosul_Ninawa_Province.html", "https://www.wego.com.co/en/hotels/iraq/mosul/hotel-modern-palace-3030351", "https://www.skyscanner.com/hotels/iraq/mosul-hotels/ci-27548340"] },
  { name: "فندق مودرن بالاس الدواسة", en: { name: "Modern Palace Dawassah", area: "Al-Dawasa" }, area: "الدواسة", bank: "right", level: 1, price: null, unit: "night",
    img: photo("hotels/modern-palace-dawasa.jpg"), sources: ["https://www.booking.com/airport/iq/osm.html", "https://www.viamichelin.co.uk/maps/hotels/poi/al_mawsil-41015-2d9e2067", "https://www.iraqiguide.com/ar/hotel/modern-palace-hotel-2"] },
  { name: "فندق مودرن بلازا إنترناشونال", en: { name: "Modern Plaza International Hotel", area: "" }, area: "", bank: "unknown", level: 2, price: null, unit: "night",
    img: photo("hotels/modern-plaza-international.jpg"), sources: ["https://www.tripadvisor.com/Hotel_Review-g303963-d23978805-Reviews-Modern_Plaza_International_Hotel-Mosul_Ninawa_Province.html", "https://www.tripadvisor.com/Hotels-g303963-Mosul_Ninawa_Province-Hotels.html", "https://iraqiguide.com/hotel/modern-plaza-international-hotel", "https://www.iraqiguide.com/ar/hotel/modern-plaza-international-hotel"] },
  { name: "فندق ليالي بغداد", en: { name: "Baghdad Nights Hotel", area: "Al-Dawasa" }, area: "الدواسة", bank: "right", level: 1, price: 31, unit: "night",
    img: photo("hotels/baghdad-nights.jpg"), sources: ["https://ph.trip.com/hotels/mosul-hotel-detail-122987278/baghdad-nights-hotel", "https://ae.trip.com/threestars/province/iq-nineveh.html", "https://www.tripadvisor.com/Hotels-g303963-Mosul_Ninawa_Province-Hotels.html", "https://in.trip.com/hotels/mosul-hotel-detail-122987278/baghdad-nights-hotel/", "https://www.iraqiguide.com/ar/hotel/baghdad-nights", "https://www.skyscanner.gg/hotels/iraq/mosul-hotels/baghdad-nights-hotel/ht-222270855"] },
  { name: "فندق رويال سيتي", en: { name: "Royal City Hotel", area: "Near Mosul amusement park" }, area: "قرب مدينة ألعاب الموصل", bank: "left", level: 2, price: null, unit: "night",
    img: photo("hotels/royal-city.jpg"), sources: ["https://nz.trip.com/hotels/mosul-hotel-detail-112316164/royal-city", "https://ph.trip.com/hotels/mosul-hotel-detail-112316164/royal-city", "https://www.tripadvisor.com/Hotels-g303963-Mosul_Ninawa_Province-Hotels.html"] },
  { name: "فندق قهرمانة", en: { name: "Kahramana Hotel", area: "Near the Old City" }, area: "قرب المدينة القديمة", bank: "unknown", level: 1, price: null, unit: "night",
    img: photo("hotels/kahramana.jpg"), sources: ["https://www.tripadvisor.co.uk/Hotels-g303963-Mosul_Ninawa_Province-Hotels.html", "https://www.laurewanders.com/things-to-do-in-mosul/", "https://www.tripadvisor.com/Hotel_Review-g303963-d33496355-Reviews-Kahramana_Hotel-Mosul_Ninawa_Province.html", "https://www.iraqiguide.com/hotel/kahramana", "https://www.facebook.com/p/%D9%81%D9%86%D8%AF%D9%82-%D9%83%D9%87%D8%B1%D9%85%D8%A7%D9%86%D8%A9_Kahramana-Hotel-100063798415103/"] },
  { name: "فندق السفير", en: { name: "Al-Safir Hotel", area: "Al-Dawasa, Aleppo Street" }, area: "الدواسة، شارع حلب", bank: "right", level: 1, price: null, unit: "night",
    img: photo("hotels/al-safir.jpg"), sources: ["https://againstthecompass.com/en/visit-mosul-iraq-after-liberation/", "https://www.laurewanders.com/things-to-do-in-mosul/", "https://www.tripadvisor.com/Hotels-g303963-Mosul_Ninawa_Province-Hotels.html", "https://www.iraqiguide.com/hotel/alsafeer", "https://www.iraqiguide.com/ar/hotel/alsafeer", "https://en.wikivoyage.org/wiki/Nineveh", "https://www.50besthotels.com/city/mosul"] },
  { name: "فندق البارون", en: { name: "Al-Baron Hotel", area: "Old Bridge corniche" }, area: "كورنيش الجسر العتيق", bank: "unknown", level: 2, price: null, unit: "night",
    img: photo("hotels/al-baron.jpg"), sources: ["https://aurum-transfers.com/global/hotels/mosul-iq", "https://id.trip.com/hotels/mosul-hotels-list-86793", "https://www.laurewanders.com/things-to-do-in-mosul/", "https://iraqiguide.com/hotel/al-baron", "https://www.iraqiguide.com/ar/hotel/al-baron", "https://www.booking.com/airport/iq/osm.html", "https://www.wego.vn/en/hotels/iraq/mosul/al-baron-hotel-mosul-3350019"] },
  { name: "فندق أبراج المدينة", en: { name: "Abraj Al Madina Hotel", area: "Al-Maliya district" }, area: "منطقة المالية", bank: "unknown", level: 2, price: null, unit: "night",
    img: photo("hotels/abraj-al-madina.jpg"), sources: ["https://mcoc.org.iq/2024/10/31/%D8%A7%D9%81%D8%AA%D8%AA%D8%A7%D8%AD-%D9%81%D9%86%D8%AF%D9%82-%D8%A7%D8%A8%D8%B1%D8%A7%D8%AC-%D8%A7%D9%84%D9%85%D8%AF%D9%8A%D9%86%D8%A9-%D9%81%D9%8A-%D8%A7%D9%84%D9%85%D9%88%D8%B5%D9%84/", "https://www.tripadvisor.com/Hotels-g303963-Mosul_Ninawa_Province-Hotels.html", "https://www.booking.com/airport/iq/osm.html"] },
  { name: "فندق باشطابيا", en: { name: "Bashtabia Hotel", area: "Al-Muhandiseen" }, area: "حي المهندسين", bank: "left", level: 2, price: null, unit: "night",
    img: photo("hotels/bashtabia.jpg"), sources: ["https://www.instagram.com/bachtabia_hotel/", "https://www.iraqiguide.com/hotel/bashtabia-hotel", "https://iraqiguide.com/ar/hotel/bashtabia-hotel"] },
  { name: "فندق منارة التراثي", en: { name: "Manara Heritage Hotel", area: "Old City, near al-Nuri Mosque" }, area: "المدينة القديمة قرب جامع النوري", bank: "right", level: 2, price: null, unit: "night",
    img: photo("hotels/manara-heritage.jpg"), sources: ["https://shafaq.com/en/society/First-heritage-hotel-revitalizes-war-torn-old-Mosul", "https://964media.com/516682/", "https://www.iraqiguide.com/hotel/manara"] },
  { name: "فندق سما المطار", en: { name: "Sky Airport Hotel", area: "Near Mosul Airport" }, area: "قرب مطار الموصل", bank: "right", level: 2, price: null, unit: "night",
    img: photo("hotels/sky-airport.jpg"), sources: ["https://www.booking.com/airport/iq/osm.html", "https://www.viamichelin.de/karten-stadtplan/hotels/poi/al_mawsil-41015-1fdf9435"] },
  { name: "موتيل نركال", en: { name: "Motel Nergal", area: "" }, area: "", bank: "unknown", level: 2, price: null, unit: "night",
    img: photo("hotels/motel-nergal.jpg"), sources: ["https://www.facebook.com/MotelNerkal/", "https://www.50besthotels.com/city/mosul"] },
];

const RESTAURANTS = [
  { name: "كبة الحدباء", cuisine: "كبة موصلية", en: { name: "Hadba Kibbeh", cuisine: "Kubba Mosuli", area: "Old City, near al-Nuri Mosque" }, area: "المدينة القديمة قرب جامع النوري", bank: "right", kind: "traditional", level: 1, price: null, unit: "person",
    img: photo("restaurants/hadba-kibbeh.jpg"), sources: ["https://www.iraqtourism.org/iraqi-food/", "https://davidsbeenhere.com/2023/11/18/mosul-iraq-ultimate-travel-guide/", "https://voiceofguides.com/ultimate-travel-guide-to-mosul/"] },
  { name: "مطعم إيوان", cuisine: "مشويات وأكلات شعبية", en: { name: "Iwan Restaurant", cuisine: "Grills and street food", area: "Old Mosul" }, area: "الموصل القديمة", bank: "right", kind: "grill", level: 1, price: null, unit: "person",
    img: photo("restaurants/iwan.jpg"), sources: ["https://www.tripadvisor.com/Restaurants-g303963-Mosul_Ninawa_Province.html", "https://www.tripadvisor.com/Restaurants-g303963-c30-Mosul_Ninawa_Province.html", "https://uk.trip.com/travel-guide/foods/Mosul-24912-restaurant/Iwan%20Restaurant-140630260", "https://www.tripadvisor.com.au/Restaurant_Review-g303963-d25320227-Reviews-Iwan_Restaurant-Mosul_Ninawa_Province.html", "https://www.tiktok.com/discover/%D8%A7%D9%81%D8%B6%D9%84-%D9%85%D8%B7%D8%B9%D9%85-%D9%81%D9%8A-%D9%85%D9%88%D8%B5%D9%84"] },
  { name: "باجة الأندلس", cuisine: "باجة موصلية", en: { name: "Bacha Al-Andalus", cuisine: "Mosuli pacha", area: "Al-Shurta, opposite the Forests" }, area: "حي الشرطة مقابل الغابات", bank: "left", kind: "traditional", level: 1, price: null, unit: "person",
    img: photo("restaurants/bacha-andalus.jpg"), sources: ["https://www.tripadvisor.com/Restaurants-g303963-zfp9-Mosul_Ninawa_Province.html", "https://www.instagram.com/bjlndls/", "https://www.tripadvisor.com/Restaurant_Review-g303963-d26868717-Reviews-Bacha_Al_Andalus_Popular_Restaurant-Mosul_Ninawa_Province.html"] },
  { name: "مطعم خالد أبو الكص", cuisine: "كص (شاورما عراقية)", en: { name: "Khaled Abu Al-Kass", cuisine: "Iraqi kass (shawarma)", area: "Al-Mansa Street" }, area: "شارع المنصة", bank: "unknown", kind: "grill", level: 1, price: null, unit: "person",
    img: photo("restaurants/khaled-abu-alkass.jpg"), sources: ["https://thepointsoflife.boardingarea.com/mosul-iraq-day-1-the-best-homemade-food-in-the-world/", "https://www.tripadvisor.com/Restaurant_Review-g303963-d25337078-Reviews-Khaled_Abu_Al_Kass_Restaurant-Mosul_Ninawa_Province.html", "https://www.top-rated.online/countries/Iraq/cities/Mosul/@restaurant"] },
  { name: "مطعم أبو ليلى", cuisine: "كباب ومشويات عراقية", en: { name: "Abu Layla Restaurant", cuisine: "Iraqi kebab and grills", area: "Left bank" }, area: "الساحل الأيسر", bank: "left", kind: "grill", level: 1, price: null, unit: "person",
    img: photo("restaurants/abu-layla.jpg"), sources: ["https://evendo.com/locations/iraq/mosul/restaurant/abu-layla-2", "https://www.top-rated.online/countries/Iraq/cities/Mosul/@restaurant", "https://arabi21.com/story/1142278"] },
  { name: "بيت أمي", cuisine: "طبخ موصلي بيتي", en: { name: "Beit Ummi", cuisine: "Home-style Mosuli cooking", area: "Old City" }, area: "المدينة القديمة", bank: "right", kind: "traditional", level: 2, price: null, unit: "person",
    img: photo("restaurants/beit-ummi.jpg"), sources: ["https://reuters.screenocean.com/record/1830533"] },
  { name: "مطعم وايت فوكس", cuisine: "قائمة متنوعة يقدّمها روبوت", en: { name: "White Fox Restaurant", cuisine: "Mixed menu served by robots", area: "" }, area: "", bank: "unknown", kind: "traditional", level: 2, price: null, unit: "person",
    img: photo("restaurants/white-fox.jpg"), sources: ["https://www.masrawy.com/news/news_publicaffairs/details/2021/11/22/2127772/روبوتات-تنقل-زبائن-مطعم-بالموصل-في-رحلة-نحو-المستقبل", "https://www.kurdistan24.net/ar/story/306563", "https://www.voanews.com/amp/6370344.html", "https://www.africanews.com/amp/2021/11/22/robot-waiters-take-iraqis-in-mosul-into-the-future/"] },
  { name: "مطعم سيدتي الجميلة", cuisine: "أكلات عراقية", en: { name: "Sayidati al-Jamila Restaurant", cuisine: "Iraqi", area: "Al-Zuhoor" }, area: "حي الزهور", bank: "left", kind: "traditional", level: 2, price: null, unit: "person",
    img: photo("restaurants/sayidati-jamila.jpg"), sources: ["https://www.pressreader.com/uae/the-national-news/20170211/281659664788390", "https://antiguaobserver.com/?p=151844", "https://evendo.com/locations/iraq/mosul/best-restaurants"] },
  { name: "مطعم الشيف أحمد السويدي", cuisine: "أطباق أوروبية بنكهة موصلية", en: { name: "Chef Ahmed Al-Suwaidi", cuisine: "European dishes with Mosuli flavours", area: "Opposite Qara Saray on the Tigris" }, area: "مقابل قره سراي على دجلة", bank: "right", kind: "cafe", level: 2, price: null, unit: "person",
    img: photo("restaurants/chef-ahmed.jpg"), sources: ["https://www.al-monitor.com/originals/2024/09/nightlife-now-rules-iraqs-former-bastion", "https://www.omandaily.om/ampArticle/1164301"] },
  { name: "مقهى بيتنا", cuisine: "مقهى تراثي", en: { name: "Baytna Tea House", cuisine: "Heritage tea house", area: "Al-Farouq quarter, Old City" }, area: "محلة الفاروق، المدينة القديمة", bank: "right", kind: "cafe", level: 1, price: null, unit: "person",
    img: photo("restaurants/baytna-tea-house.jpg"), sources: ["https://travelinsighter.com/ancient-nineveh-to-isis-one-day-in-mosul-iraq/", "https://masaratiraq.org/2026/01/10/dialogue-camp-explores-the-historical-landmarks-of-mosuls-spirit/"] },
  { name: "منتدى الكتاب", cuisine: "مقهى ثقافي", en: { name: "Mosul Book Forum", cuisine: "Literary café", area: "" }, area: "", bank: "unknown", kind: "cafe", level: 1, price: null, unit: "person",
    img: photo("restaurants/mosul-book-forum.jpg"), sources: ["https://www.al-monitor.com/originals/2018/12/mosul-book-forum-grows-with-donations.html", "https://www.arabnews.com/node/1943541/middle-east", "https://english.ahram.org.eg/UI/Front/Inner.aspx?NewsContentID=289418"] },
  { name: "مذاق الموصل", cuisine: "طبخ موصلي بيتي وتموين", en: { name: "Taste of Mosul", cuisine: "Mosuli home cooking and catering", area: "" }, area: "", bank: "unknown", kind: "traditional", level: 2, price: null, unit: "person",
    img: photo("restaurants/taste-of-mosul.jpg"), sources: ["https://www.arabnews.com/node/2378491", "https://arabic.euronews.com/2023/09/22/iraq-mosul-women-widowed-divorced-empowering-restaurant-catering-food-business-independenc"] },
  { name: "مطعم أبو جنى", cuisine: "مسكوف ومأكولات بحرية", en: { name: "Abo Jana Seafood", cuisine: "Masgouf and seafood", area: "" }, area: "", bank: "unknown", kind: "grill", level: 2, price: null, unit: "person",
    img: photo("restaurants/abo-jana.jpg"), sources: ["https://travelinsighter.com/iraqi-traditional-foods-dishes-you-must-try/", "https://mindtrip.ai/restaurant/mosul-ninawa/abo-jana/re-NjJFF1eb", "https://www.top-rated.online/countries/Iraq/cities/Mosul/@restaurant"] },
  { name: "مطعم سراي", cuisine: "أكلات عراقية", en: { name: "Saray Restaurant", cuisine: "Iraqi and Middle Eastern", area: "" }, area: "", bank: "unknown", kind: "traditional", level: 2, price: null, unit: "person",
    img: photo("restaurants/saray.jpg"), sources: ["https://uk.trip.com/travel-guide/foods/Mosul-24912-restaurant/Saray%20Resturant-137223391", "https://www.facebook.com/saray.mosul/", "https://www.top-rated.online/countries/Iraq/cities/Mosul/@restaurant"] },
  { name: "مطعم خطار", cuisine: "أكلات عراقية تقليدية", en: { name: "Khattar Restaurant", cuisine: "Traditional Iraqi", area: "" }, area: "", bank: "unknown", kind: "traditional", level: 1, price: null, unit: "person",
    img: photo("restaurants/khattar.jpg"), sources: ["https://evendo.com/locations/iraq/mosul/restaurant/khattar-restaurant", "https://www.top-rated.online/countries/Iraq/cities/Mosul/@restaurant", "https://www.tiktok.com/discover/%D9%85%D8%B7%D8%B9%D9%85-%D8%AE%D8%B7%D8%A7%D8%B1-%D9%81%D9%8A-%D8%A7%D9%84%D9%85%D9%88%D8%B5%D9%84"] },
];

const POST_SERVICES = [
  { icon: "scissors", title: "المونتاج", text: "بناء الإيقاع والسرد على Avid و Premiere مع مونتير متخصص في نوع مشروعك.",
    en: { title: "Editing", text: "Pacing and story built on Avid and Premiere by an editor who knows your genre." } },
  { icon: "palette", title: "تصحيح الألوان", text: "تلوين سينمائي على DaVinci Resolve بشاشات مرجعية معايَرة.",
    en: { title: "Color Grading", text: "Cinematic grading in DaVinci Resolve on calibrated reference monitors." } },
  { icon: "sparkle", title: "المؤثرات البصرية", text: "تركيب، تتبّع، تنظيف لقطات ورسوميات متحركة.",
    en: { title: "Visual Effects", text: "Compositing, tracking, cleanup and motion graphics." } },
  { icon: "wave", title: "التصميم الصوتي", text: "مكساج، مؤثرات صوتية، وتسجيل تعليق صوتي في استوديو معزول.",
    en: { title: "Sound Design", text: "Mixing, sound effects and voice-over recording in an isolated booth." } },
];

const PACKAGES = [
  { name: "الأساسية", price: 300, unit: "project", note: "للمحتوى القصير والسوشال ميديا",
    features: ["مونتاج حتى 3 دقائق", "تصحيح ألوان أساسي", "موسيقى مرخّصة", "جولتا تعديل", "تسليم خلال 5 أيام"],
    en: { name: "Basic", note: "For short-form and social content",
      features: ["Edit up to 3 minutes", "Basic color correction", "Licensed music", "2 revision rounds", "Delivery in 5 days"] } },
  { name: "الاحترافية", price: 800, unit: "project", note: "للإعلانات التجارية والكليبات", featured: true,
    features: ["مونتاج حتى 10 دقائق", "تلوين سينمائي كامل", "مكساج وتصميم صوتي", "مؤثرات بصرية بسيطة", "4 جولات تعديل", "نسخ لجميع المنصات"],
    en: { name: "Professional", note: "For commercials and music videos",
      features: ["Edit up to 10 minutes", "Full cinematic grade", "Mixing & sound design", "Light visual effects", "4 revision rounds", "Cuts for every platform"] } },
  { name: "المتكاملة", price: 1500, unit: "from", note: "للأفلام والوثائقيات الطويلة",
    features: ["مونتاج غير محدود المدة", "تلوين بإشراف ملوّن رئيسي", "مؤثرات بصرية متقدمة", "مكساج 5.1 للسينما", "ترجمة وتعليق صوتي", "تعديلات غير محدودة", "تسليم DCP للمهرجانات"],
    en: { name: "Complete", note: "For features and long-form documentaries",
      features: ["Unlimited runtime edit", "Grade supervised by a lead colorist", "Advanced visual effects", "5.1 theatrical mix", "Subtitles & voice-over", "Unlimited revisions", "DCP delivery for festivals"] } },
];
